# Generated by Django 4.1 on 2023-03-30 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_create_date_post_created_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="create_date",
            new_name="created_date",
        ),
    ]
