# Generated by Django 4.1.7 on 2023-03-30 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_create_date_comment_created_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="approved_comments",
            new_name="approved_comment",
        ),
    ]
